# Site Settings
title: B-Log
email: deepakc3010@gmail.com
description: Discover. Learn. Read. 
#baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "https://dc430.github.io" # the base hostname & protocol for your site
#google_analytics: "UA-121195984-1"

# User Settings
username: Deepak Chauhan
user_description: Admin
disqus_username: dc430

# Social Media
# Remove the item if you don't need it
github_username: dc430
facebook_username: ddlef
twitter_username: dc430
instagram_username: dc430
linkedin_username: deepak-chauhan-7896b313b
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Categories
    url: /categories/

authors:
  deepak:
    name: Deepak Chauhan
    display_name: Deepak 
    image_url: '/assets/img/authors/deepak.jpg'
    desc: Nothing here.
  rashika:
    name: Rashika Chauhan
    display_name: Rashika
    desc: Nothing to see here.


# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
